version: '3'

services:
 myDB:
  image: postgres:17
  container_name:
  restart: always
  ports:
   - 5432:5432
  environment:
   - POSTGRES_USER=
   - POSTGRES_PASSWORD=
   - POSTGRES_DB=
  volumes:
   - ./postgres:/var/lib/postgresql/data

 pdAdmin:
  image: dpage/pgadmin4
  container_name: pgadmin4
  restart: always
  depends_on:
   - myDB
  ports:
   - 8080:80
  environment:
   - PGADMIN_DEFAULT_EMAIL=
   - PGADMIN_DEFAULT_PASSWORD=
  volumes:
   - ./pgadmin:/var/lib/pgadmin
   - ./pgadmin:/certs/server.cert
   - ./pgadmin:/certs/server.key
   - ./pgadmin:/pgadmin4/servers.json